#!/bin/bash

if [[ $# -lt 2 ]] || [[ $# -gt 3 ]] ; then
        echo "USAGE: $(basename $0) device mount-point [label]">&2
        exit 1
fi
if [[ ! $1 =~ ^/dev/..* ]] ; then
        echo "USAGE: $1 is not point to a /dev/ path" >&2
        exit 1
fi
if [[ ! $2 =~ ^/..* ]] ; then
        echo "USAGE: $2 is not point to an absolute path under root" >&2
        exit 1
fi

ESCAPED_MOUNT_POINT=$(sed -e 's^/^\\\\/^g' <<< $2)
sed -e "s~@@DEVICE@@~$1~g" \
	-e "s~@@ESCAPED_MOUNT_POINT@@~$ESCAPED_MOUNT_POINT~g" \
	-e "s~@@MOUNT_POINT@@~$2~g" \
	-e "s~@@LABEL@@~${3:-$2}~g" <<!
  bootcmd:
    - mkdir -p @@MOUNT_POINT@@
    - while [ ! -b \$(readlink -f @@DEVICE@@) ]; do echo "waiting for device @@DEVICE@@"; sleep 5 ; done
    - blkid \$(readlink -f @@DEVICE@@) || mkfs -t ext4 \$(readlink -f @@DEVICE@@)
    - e2label \$(readlink -f @@DEVICE@@) @@LABEL@@
    - sed  -e '/^[\/][^ \t]*[ \t]*@@ESCAPED_MOUNT_POINT@@[ \t]/d' /etc/fstab
    - grep -q ^LABEL=@@LABEL@@ /etc/fstab || echo 'LABEL=@@LABEL@@ @@MOUNT_POINT@@ ext4 defaults' >> /etc/fstab
    - grep -q "^\$(readlink -f @@DEVICE@@) @@MOUNT_POINT@@ " /proc/mounts || mount @@MOUNT_POINT@@
!
